# Generated by Django 5.2.7 on 2026-04-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pos_pin',
            field=models.CharField(blank=True, help_text='4-digit PIN for POS access', max_length=4, null=True),
        ),
    ]
