# Generated by Django 5.2.7 on 2026-04-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_family_familymembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('admin', 'Admin'), ('Chairperson', 'Chairperson'), ('Secretary', 'Secretary'), ('Accountant', 'Accountant'), ('Member', 'Member'), ('active_member', 'Active Member'), ('priest', 'Priest'), ('catechist', 'Catechist'), ('treasurer', 'Treasurer'), ('vice_chairperson', 'Vice Chairperson'), ('coordinator', 'Coordinator'), ('liturgical', 'Liturgical'), ('evangelization', 'Evangelization'), ('youth', 'Youth'), ('choir', 'Choir'), ('reader', 'Reader')], default='Member', max_length=50),
        ),
    ]
