# Generated by Django 5.2.7 on 2026-05-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_familymembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='familymembership',
            unique_together=set(),
        ),
    ]
