# Generated by Django 5.2.7 on 2026-04-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('MASS', 'Holy Mass'), ('MEETING', 'Meeting'), ('CELEBRATION', 'Celebration'), ('RETREAT', 'Retreat'), ('WORKSHOP', 'Workshop'), ('FUNDRAISER', 'Fundraiser'), ('OUTREACH', 'Community Outreach'), ('SACRAMENT', 'Sacrament'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('recurrence', models.CharField(choices=[('NONE', 'Does not repeat'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='NONE', max_length=20)),
                ('recurrence_end_date', models.DateField(blank=True, null=True)),
                ('location_details', models.TextField(blank=True, help_text='Additional location information', null=True)),
                ('requires_registration', models.BooleanField(default=False)),
                ('max_attendees', models.PositiveIntegerField(blank=True, help_text='Maximum number of attendees', null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('registration_open', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('is_public', models.BooleanField(default=True, help_text='Visible to public/non-logged users')),
                ('featured', models.BooleanField(default=False, help_text='Featured events appear prominently')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='events/attachments/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for calendar display', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Event Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dietary_requirements', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('ATTENDED', 'Attended'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20)),
                ('sms_sent', models.BooleanField(default=False)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sms_failure_count', models.PositiveIntegerField(default=0)),
                ('last_sms_error', models.TextField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['registered_at'],
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('BOTH', 'Both')], default='EMAIL', max_length=10)),
                ('minutes_before', models.PositiveIntegerField(default=1440, help_text='Minutes before event to send reminder (default 24 hours)')),
                ('sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['minutes_before'],
            },
        ),
        migrations.CreateModel(
            name='LiturgicalCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('season', models.CharField(choices=[('ADVENT', 'Advent'), ('CHRISTMAS', 'Christmas'), ('LENT', 'Lent'), ('TRIDUUM', 'Triduum'), ('EASTER', 'Easter'), ('ORDINARY', 'Ordinary Time')], max_length=20)),
                ('celebration_type', models.CharField(choices=[('SOLEMNITY', 'Solemnity'), ('FEAST', 'Feast'), ('MEMORIAL', 'Memorial'), ('OPTIONAL_MEMORIAL', 'Optional Memorial'), ('COMMEMORATION', 'Commemoration'), ('FERIAL', 'Ferial Day')], default='FERIAL', max_length=20)),
                ('color', models.CharField(help_text='Liturgical color (e.g., Green, White, Red, Purple)', max_length=20)),
                ('gospel_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('first_reading', models.CharField(blank=True, max_length=100, null=True)),
                ('psalm', models.CharField(blank=True, max_length=100, null=True)),
                ('second_reading', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Liturgical Calendar Entry',
                'verbose_name_plural': 'Liturgical Calendar',
                'ordering': ['date'],
            },
        ),
    ]
