builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate && echo \"from users.models import User; User.objects.create_superuser('emmanuel-leonard', 'admin@example.com', 'Simwimba@3008') if not User.objects.filter(username='admin').exists() else None\" | python manage.py shell && gunicorn christ_king_church.wsgi:application"

