builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py createsuperuser --no-input && gunicorn christ_king_church.wsgi"

