# Generated by Django 5.2.7 on 2026-04-25 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catechesis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catechesismember',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catechesismember',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catechesismember',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catechesismember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classattendance',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='catechesis_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='catechesis.catechesismember'),
        ),
        migrations.AddField(
            model_name='classattendance',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='catechesis.enrollment'),
        ),
        migrations.AddField(
            model_name='sacrament',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sacrament',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sacrament',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sacramentclass',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_classes', to='catechesis.catechesisinstructor'),
        ),
        migrations.AddField(
            model_name='sacramentclass',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='teaching_classes', to='catechesis.catechesisinstructor'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='sacrament_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='catechesis.sacramentclass'),
        ),
        migrations.AddField(
            model_name='classattendance',
            name='sacrament_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='catechesis.sacramentclass'),
        ),
        migrations.AddField(
            model_name='sacramentrecord',
            name='catechesis_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sacrament_records', to='catechesis.catechesismember'),
        ),
        migrations.AddField(
            model_name='sacramentrecord',
            name='completed_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sacraments_conferred', to='catechesis.sacramentclass'),
        ),
        migrations.AddField(
            model_name='sacramentrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sacramentrequest',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sacramentrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sacramentrequest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sacramentrequest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sacrament_requests', to='catechesis.catechesismember'),
        ),
        migrations.AddField(
            model_name='sacramentrequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sacramentrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sacramentclass',
            index=models.Index(fields=['sacrament_type', 'status'], name='catechesis__sacrame_e3b640_idx'),
        ),
        migrations.AddIndex(
            model_name='sacramentclass',
            index=models.Index(fields=['start_date', 'status'], name='catechesis__start_d_1083e3_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['catechesis_member', 'status'], name='catechesis__cateche_bc3eca_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['sacrament_class', 'status'], name='catechesis__sacrame_841f30_idx'),
        ),
        migrations.AddIndex(
            model_name='classattendance',
            index=models.Index(fields=['sacrament_class', 'class_date'], name='catechesis__sacrame_99da1e_idx'),
        ),
        migrations.AddIndex(
            model_name='classattendance',
            index=models.Index(fields=['enrollment', 'class_date'], name='catechesis__enrollm_60282c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classattendance',
            unique_together={('sacrament_class', 'class_date', 'enrollment')},
        ),
        migrations.AddIndex(
            model_name='sacramentrecord',
            index=models.Index(fields=['sacrament_type', 'ceremony_date'], name='catechesis__sacrame_776eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='sacramentrecord',
            index=models.Index(fields=['catechesis_member', 'status'], name='catechesis__cateche_34d227_idx'),
        ),
        migrations.AddIndex(
            model_name='sacramentrecord',
            index=models.Index(fields=['certificate_number'], name='catechesis__certifi_e08a98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sacramentrecord',
            unique_together={('catechesis_member', 'sacrament_type')},
        ),
        migrations.AlterUniqueTogether(
            name='sacramentrequest',
            unique_together={('member', 'sacrament')},
        ),
    ]
