# Generated by Django 5.2.7 on 2026-04-02 09:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('finance', '0004_tithereceipt'),
        ('member', '0003_merge_20260402_0806'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promised_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateField(blank=True, help_text='Deadline to complete the pledge', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('last_reminder_date', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='events.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='member.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Pledge',
                'verbose_name_plural': 'Event Pledges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PledgePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('MOBILE', 'Mobile Money'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sms_notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.eventpledge')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledge_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
