# Generated by Django 5.2.7 on 2026-04-02 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('finance', '0005_eventpledge_pledgepayment'),
        ('member', '0003_merge_20260402_0806'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpledge',
            name='external_name',
            field=models.CharField(blank=True, help_text='Name for non-member pledgers', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventpledge',
            name='external_phone',
            field=models.CharField(blank=True, help_text='Phone for non-member pledgers', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventpledge',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='member.member'),
        ),
        migrations.AddConstraint(
            model_name='eventpledge',
            constraint=models.UniqueConstraint(condition=models.Q(('member__isnull', False)), fields=('event', 'member'), name='unique_member_event_pledge'),
        ),
        migrations.AddConstraint(
            model_name='eventpledge',
            constraint=models.UniqueConstraint(condition=models.Q(('member__isnull', True)), fields=('event', 'external_name', 'external_phone'), name='unique_external_event_pledge'),
        ),
    ]
