# Generated by Django 5.2.7 on 2026-04-25 06:43

import django.db.models.deletion
import django.utils.timezone
import member.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('feast_name', models.CharField(blank=True, max_length=100, null=True)),
                ('feast_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Ministries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MinistryLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=250)),
                ('position', models.CharField(choices=[('CHAIR PERSON', 'Chair Person'), ('VICE CHAIR', 'Vice Chair'), ('SECRETARY', 'Secretary'), ('VICE SECRETARY', 'Vice Secretary'), ('ACCOUNTANT', 'Accountant'), ('COORDINATOR', 'Coordinator')], max_length=30)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=255, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('appointed_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ministry', 'position'],
            },
        ),
        migrations.CreateModel(
            name='TestDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('leader_name', models.CharField(blank=True, max_length=250, null=True)),
                ('leader_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=255, null=True, region=None)),
                ('leader_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ZoneLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('position', models.CharField(choices=[('CHAIRPERSON', 'Chairperson'), ('VICE CHAIR', 'Vice Chair'), ('SECRETARY', 'Secretary'), ('VICE SECRETARY', 'Vice Secretary'), ('ACCOUNTANT', 'Accountant'), ('COORDINATOR', 'Coordinator'), ('MEMBER', 'Member')], max_length=30)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=255, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('appointed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zone Leader',
                'verbose_name_plural': 'Zone Leaders',
                'ordering': ['zone', 'position'],
            },
        ),
        migrations.CreateModel(
            name='CommunityLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('leader', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('feast_name', models.TextField(blank=True, max_length=10, null=True)),
                ('feast_date', models.DateField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=255, null=True, region=None)),
                ('community_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='member.community')),
            ],
            options={
                'verbose_name': 'Community Leader',
                'verbose_name_plural': 'Community Leaders',
                'ordering': ['community_name', 'leader'],
            },
        ),
        migrations.CreateModel(
            name='CommunityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_zones', to='member.community')),
            ],
            options={
                'verbose_name': 'Community Zone Assignment',
                'verbose_name_plural': 'Community Zone Assignments',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, help_text='001PT', max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text=' Eg. +255 ', max_length=255, null=True, region=None)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardians_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('pays_tithe', models.BooleanField(default=False)),
                ('working', models.BooleanField(default=False)),
                ('schooling', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=member.models.upload_image_path)),
                ('transfered', models.BooleanField(default=False)),
                ('transfer_update', models.CharField(blank=True, max_length=250, null=True)),
                ('shepherd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.community')),
            ],
            options={
                'verbose_name_plural': 'Members',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commitee_name', models.CharField(max_length=250, null=True)),
                ('position', models.CharField(blank=True, choices=[('VICE CHAIR', 'Vice Chair'), ('SECRETARY', 'Secretary'), ('VICE SECRETARY', 'Vice Secretary'), ('ACCOUNTANT', 'Accountant'), ('CHAIRPERSON', 'Chairperson'), ('MEMBER', 'Member')], max_length=50, null=True)),
                ('description', models.CharField(blank=True, help_text='Write the Functions of your commitee ', max_length=50, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text=' Eg. +255 ', max_length=255, null=True, region=None)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member', verbose_name='commitee_names')),
            ],
        ),
        migrations.CreateModel(
            name='MemberSacrament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacrament_type', models.CharField(choices=[('baptism', 'Baptism'), ('confirmation', 'Confirmation'), ('eucharist', 'First Holy Communion'), ('reconciliation', 'Reconciliation'), ('marriage', 'Marriage'), ('holy_orders', 'Holy Orders'), ('anointing_sick', 'Anointing of the Sick')], max_length=50)),
                ('date_received', models.DateField(blank=True, help_text='Date when sacrament was received', null=True)),
                ('place_received', models.CharField(blank=True, help_text='Parish/Church where sacrament was received', max_length=255, null=True)),
                ('minister_name', models.CharField(blank=True, help_text='Priest/Deacon who administered the sacrament', max_length=255, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, help_text='Notes from catechesis verification', null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='sacrament_certificates/')),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='sacrament_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sacraments', to='member.member')),
            ],
            options={
                'verbose_name': 'Member Sacrament',
                'verbose_name_plural': 'Member Sacraments',
                'ordering': ['-created_at'],
            },
        ),
    ]
