# Generated by Django 5.2.7 on 2026-01-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='new_believer_school',
            field=models.BooleanField(default=False),
        ),
    ]
