# Generated by Django 5.2.7 on 2026-04-25 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membersacrament',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_sacraments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membersacrament',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sacrament_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membersacrament',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sacraments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.ministry'),
        ),
        migrations.AddField(
            model_name='ministryleader',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ministry_leaders', to='member.community', verbose_name='Community'),
        ),
        migrations.AddField(
            model_name='ministryleader',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Select a member to autopopulate details', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ministry_leaders', to='member.member'),
        ),
        migrations.AddField(
            model_name='ministryleader',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='member.ministry'),
        ),
        migrations.AddField(
            model_name='communityzone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_zones', to='member.zone'),
        ),
        migrations.AddField(
            model_name='zoneleader',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='member.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='communityleader',
            unique_together={('community_name', 'leader')},
        ),
        migrations.AlterUniqueTogether(
            name='membersacrament',
            unique_together={('member', 'user', 'sacrament_type')},
        ),
        migrations.AlterUniqueTogether(
            name='ministryleader',
            unique_together={('ministry', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='communityzone',
            unique_together={('zone', 'community')},
        ),
        migrations.AlterUniqueTogether(
            name='zoneleader',
            unique_together={('zone', 'position')},
        ),
    ]
