# Generated by Django 5.2.7 on 2026-04-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_category',
            field=models.CharField(blank=True, choices=[('elder', 'Elder'), ('youth', 'Youth'), ('child', 'Child')], help_text='Distinguishes between Elders, Youth, and Children', max_length=10, null=True),
        ),
    ]
