# Generated by Django 5.2.7 on 2026-04-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_new_believer_school'),
        ('member', '0002_alter_ministry_created_at'),
    ]

    operations = [
    ]
