# Generated by Django 5.2.7 on 2026-05-14 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_membership_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='member.ministry'),
        ),
        migrations.AlterField(
            model_name='member',
            name='shepherd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='member.community'),
        ),
    ]
