# Generated by Django 5.2.7 on 2026-01-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tithe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tithepayment',
            name='contact_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='tithereceipt',
            name='church_phone',
            field=models.CharField(blank=True, default='+255 XXX XXX XXX', max_length=20, null=True),
        ),
    ]
