# Generated by Django 5.2.7 on 2026-08-03 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_ministry_alter_member_shepherd'),
        ('tithe', '0002_deviceregistration_offlineoperation_synclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tithepayment',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Guest Name'),
        ),
        migrations.AlterField(
            model_name='tithepayment',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member', verbose_name='Member'),
        ),
    ]
