# Generated by Django 5.2.7 on 2026-04-25 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('network_code', models.CharField(blank=True, max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('message_id', models.CharField(max_length=50, unique=True)),
                ('link_id', models.CharField(blank=True, max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Incoming SMS',
                'verbose_name_plural': 'Incoming SMS',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('at_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-read_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent_via_websocket', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(help_text='Message content (max 160 characters for single SMS)')),
                ('recipient_type', models.CharField(choices=[('MEMBER', 'Individual Member'), ('MINISTRY', 'Ministry Members'), ('COMMUNITY', 'Community Members'), ('ALL', 'All Active Members'), ('Staff', 'All Active Staff'), ('PORTAL_MEMBERS', 'All Portal Members'), ('COMMUNITY_LEADERS', 'All Community Leaders'), ('MINISTRY_LEADERS', 'All Ministry Leaders'), ('ZONE_LEADERS', 'All Zone Leaders'), ('TITHE_PAYERS', 'Members Who Pay Tithe'), ('PLEDGERS', 'Members with Active Pledges'), ('CUSTOM_PHONES', 'Custom Phone Numbers')], max_length=20)),
                ('target_audience', models.CharField(choices=[('ALL', 'All Users'), ('STAFF_ONLY', 'Staff Only'), ('MEMBERS_ONLY', 'Members Only'), ('PORTAL_ONLY', 'Portal Members Only')], default='ALL', help_text='Who should receive this notification in the portal/app', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Notification priority level', max_length=10)),
                ('custom_phone_numbers', models.TextField(blank=True, help_text='Enter phone numbers separated by commas (e.g., +255712345678, +255723456789)', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('send_sms', models.BooleanField(default=True, help_text='Send SMS via AfricasTalking')),
                ('total_recipients', models.IntegerField(default=0)),
                ('sms_sent_count', models.IntegerField(default=0)),
                ('sms_failed_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='member.community')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
