# Generated by Django 5.2.7 on 2026-05-04 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_membership_category'),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='zone',
        ),
        migrations.AddField(
            model_name='notification',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='member.committee'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('MINISTRY', 'Ministry'), ('COMMITTEE', 'Committee'), ('COMMUNITY', 'Community'), ('ALL', 'All'), ('TITHE_PAYERS', 'Tithe_payer'), ('CUSTOM_PHONES', 'Custom_phones')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'All_Users'), ('STAFF_ONLY', 'Staff_Only'), ('MEMBERS_ONLY', 'Members_Only'), ('PORTAL_ONLY', 'Portal_Only')], default='ALL', help_text='Who should receive this notification in the portal/app', max_length=20),
        ),
    ]
